# Anycable
anycable_redis_url: redis://127.0.0.1:6379/1
anycable_rpc_host: 127.0.0.1:50051

# Tooling
tooling_redis_url: redis://127.0.0.1:6379/3
snippet_generator_url: http://local.exercism.io:3024/extract_snippet
lines_of_code_counter_url: http://local.exercism.io:3025/count_lines_of_code
chatgpt_proxy_url: http://local.exercism.io:3026/ask_chatgpt
tooling_cloudwatch_jobs_log_group_name: "/tooling-jobs"
tooling_cloudwatch_jobs_log_stream_name: "general"

# DynamoDB config
dynamodb_tooling_jobs_table: tooling_jobs
dynamodb_tooling_language_groups_table: tooling_language_groups

# Internal Routes
spi_url: http://local.exercism.io:3020
tooling_orchestrator_url: http://local.exercism.io:3021
language_server_url: ws://local.exercism.io:3023
image_generator: http://local.exercism.io:3024

# MySQL
mysql_master_endpoint: localhost
mysql_port: null

# S3 Config
aws_submissions_bucket: exercism-v3-submissions
aws_tooling_jobs_bucket: exercism-v3-tooling-jobs

# Hosts
website_icons_host: https://assets.exercism.org
website_assets_host: https://assets.exercism.org
website_avatars_host: http://local.exercism.io:3020/avatars
website_assets_cloudfront_distribution_id: "123456"

# Sidekiq Config
sidekiq_redis_url: redis://127.0.0.1:6379/2

# EFS Config
efs_submissions_mount_point: "/opt/exercism/efs/submissions"
efs_repositories_mount_point: "/opt/exercism/efs/repos"

# GitHub Config
github_organization: fake-exercism
github_bot_username: exercism-bot

# OpenSearch
opensearch_host: https://localhost:9200

# Extra things not used in development, but here
# so that this file can provide a reference
aws_attachments_bucket:
aws_attachments_region:

# PayPal
paypal_api_url: https://api-m.sandbox.paypal.com
paypal_url: https://www.sandbox.paypal.com

mongodb_url: 'mongodb://127.0.0.1:27017'
mongodb_database_name: 'exercism'
