anycable_redis_url: redis://127.0.0.1:6379/1
anycable_rpc_host: 127.0.0.1:50051
aws_submissions_bucket: exercism-staging-submissions
aws_tooling_jobs_bucket: exercism-staging-tooling-jobs
dynamodb_tooling_jobs_table: tooling_jobs
dynamodb_tooling_language_groups_table: tooling_language_groups
mysql_master_endpoint: localhost
mysql_socket: /tmp/mysql.sock
spi_url: http://127.0.0.1:3020
tooling_orchestrator_url: http://127.0.0.1:3021
language_server_url: ws://127.0.0.1:3023
