# Anycable
anycable_redis_url: redis://127.0.0.1:6379/1
anycable_rpc_host: 127.0.0.1:50051

# Tooling
tooling_redis_url: redis://127.0.0.1:6379/3

# DynamoDB config
dynamodb_tooling_jobs_table: tooling_jobs
dynamodb_tooling_language_groups_table: tooling_language_groups

# Internal Routes
language_server_url: ws://local.exercism.io:3023
spi_url: http://local.exercism.io:3020
tooling_orchestrator_url: http://local.exercism.io:3021

# MySQL
mysql_master_endpoint: localhost
mysql_socket: /tmp/mysql.sock
mysql_port: null

# S3 Config
aws_submissions_bucket: exercism-v3-submissions
aws_tooling_jobs_bucket: exercism-v3-tooling-jobs

# Hosts
website_icons_host: https://exercism-v3-icons.s3.eu-west-2.amazonaws.com
website_assets_host:

# Sidekiq Config
sidekiq_redis_url: redis://127.0.0.1:6379/2

# EFS Config
efs_submissions_mount_point: "/tmp/exercism/efs/submissions"
efs_repositories_mount_point: "/tmp/exercism/efs/repos"

# GitHub Config
github_organization: fake-exercism
github_bot_username: exercism-bot

# OpenSearch
opensearch_host: https://localhost:9200

# Extra things not used in development, but here
# so that this file can provide a reference
aws_attachments_bucket:
aws_attachments_region:
